"""
Agent Protocol — Session Binding (X25519 + HKDF + HMAC-SHA256).

Provides cryptographic binding between a client and a session so that
knowing (or guessing) the session UUID alone is insufficient to hijack
the session, and so that a passive observer of the handshake cannot
forge binding proofs.

Flow (key agreement, the default):
    1. Client generates ``client_nonce`` and an ephemeral X25519 key pair
       and sends its public key as ``client_ephemeral_key`` in
       ``session.init``.
    2. Server generates ``server_nonce``, ``confirm_nonce`` and its own
       ephemeral X25519 key pair, and sends its public key as
       ``server_ephemeral_key`` in ``session.established``. The binding
       key is NEVER transmitted.
    3. Both sides compute the X25519 shared secret and derive the binding
       key with :func:`derive_session_binding_key` (HKDF-SHA256 over the
       shared secret, session_id, both nonces and both public keys).
    4. Client sends ``binding_proof = HMAC(key, transcript)`` (see
       :func:`compute_binding_proof`); the server MUST verify it with
       :func:`verify_binding_proof` before activating the session.
    5. Each subsequent message carries a ``Session-Binding`` header:
       ``HMAC(key, session_id || 0x00 || message_id || 0x00 || hex(SHA-256(canonical body)))``
       (see :func:`create_message_binding`).

``derive_binding_token`` (pre-shared-secret derivation) is retained for
deployments with an out-of-band PSK.

This module is PURE — stdlib, pydantic and ``cryptography`` only.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
from typing import Any

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric.x25519 import (
    X25519PrivateKey,
    X25519PublicKey,
)
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from pydantic import BaseModel, Field

_HKDF_INFO_LABEL = "ampro-session-binding-v1"
_CONFIRM_LABEL = "ampro-session-confirm-v1"

# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------


class SessionBinding(BaseModel):
    """Captures the binding state negotiated during session handshake.

    ``binding_token`` is the derived secret binding key (hex). It is held
    locally by each peer and MUST NOT be transmitted.
    """

    session_id: str = Field(
        description="Unique session identifier (UUID) this binding is tied to",
    )
    binding_token: str = Field(
        description="Hex-encoded 32-byte binding key (never sent on the wire)",
    )
    client_nonce: str = Field(
        description="Random nonce generated by the client during handshake",
    )
    server_nonce: str = Field(
        description="Random nonce generated by the server during handshake",
    )
    client_public_key: str = Field(
        default="",
        description="Client ephemeral X25519 public key (base64url, no padding)",
    )
    server_public_key: str = Field(
        default="",
        description="Server ephemeral X25519 public key (base64url, no padding)",
    )
    confirm_nonce: str = Field(
        default="",
        description="confirm_nonce issued in session.established",
    )

    model_config = {"extra": "ignore"}


# ---------------------------------------------------------------------------
# Ephemeral key agreement
# ---------------------------------------------------------------------------


def _b64url_encode(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def _b64url_decode(value: str) -> bytes:
    pad = "=" * (-len(value) % 4)
    return base64.b64decode(value + pad, altchars=b"-_", validate=True)


def generate_ephemeral_keypair() -> tuple[X25519PrivateKey, str]:
    """Generate an ephemeral X25519 key pair.

    Returns:
        ``(private_key, public_key_b64url)`` — the public key is the raw
        32-byte X25519 key, base64url-encoded without padding.
    """
    private_key = X25519PrivateKey.generate()
    public = private_key.public_key().public_bytes_raw()
    return private_key, _b64url_encode(public)


def derive_session_binding_key(
    private_key: X25519PrivateKey,
    peer_public_key: str,
    *,
    session_id: str,
    client_nonce: str,
    server_nonce: str,
    client_public_key: str,
    server_public_key: str,
) -> str:
    """Derive the session binding key from an X25519 exchange.

    ``key = HKDF-SHA256(ikm=X25519(priv, peer_pub),
                        salt=UTF8(client_nonce || 0x00 || server_nonce),
                        info=UTF8("ampro-session-binding-v1" || 0x00 ||
                                  session_id || 0x00 ||
                                  client_public_key || 0x00 ||
                                  server_public_key),
                        L=32)``

    Returns:
        The 32-byte key, hex-encoded (64 chars).

    Raises:
        ValueError: On a malformed peer key or an all-zero shared secret
            (low-order point).
    """
    try:
        peer_raw = _b64url_decode(peer_public_key)
    except Exception as exc:
        raise ValueError("peer ephemeral key is not valid base64url") from exc
    if len(peer_raw) != 32:
        raise ValueError("peer ephemeral key must be 32 bytes")
    shared = private_key.exchange(X25519PublicKey.from_public_bytes(peer_raw))
    if not any(shared):
        raise ValueError("X25519 shared secret is all-zero (low-order peer key)")
    info = "\x00".join(
        (_HKDF_INFO_LABEL, session_id, client_public_key, server_public_key)
    ).encode("utf-8")
    salt = (client_nonce + "\x00" + server_nonce).encode("utf-8")
    key = HKDF(algorithm=hashes.SHA256(), length=32, salt=salt, info=info).derive(shared)
    return key.hex()


def _confirm_transcript(
    *,
    session_id: str,
    client_nonce: str,
    server_nonce: str,
    confirm_nonce: str,
    client_public_key: str,
    server_public_key: str,
) -> bytes:
    return "\x00".join(
        (
            _CONFIRM_LABEL,
            session_id,
            client_nonce,
            server_nonce,
            confirm_nonce,
            client_public_key,
            server_public_key,
        )
    ).encode("utf-8")


def compute_binding_proof(
    binding_token: str,
    *,
    session_id: str,
    client_nonce: str,
    server_nonce: str,
    confirm_nonce: str,
    client_public_key: str,
    server_public_key: str,
) -> str:
    """Compute the ``binding_proof`` sent in ``session.confirm``.

    ``HMAC-SHA256(key=UTF8(binding_token), msg="ampro-session-confirm-v1"
    || 0x00 || session_id || 0x00 || client_nonce || 0x00 || server_nonce
    || 0x00 || confirm_nonce || 0x00 || client_public_key || 0x00 ||
    server_public_key)`` as lowercase hex.
    """
    if not binding_token:
        raise ValueError("binding_token must not be empty")
    msg = _confirm_transcript(
        session_id=session_id,
        client_nonce=client_nonce,
        server_nonce=server_nonce,
        confirm_nonce=confirm_nonce,
        client_public_key=client_public_key,
        server_public_key=server_public_key,
    )
    return hmac.new(binding_token.encode("utf-8"), msg, hashlib.sha256).hexdigest()


def verify_binding_proof(
    binding_token: str,
    provided_proof: str,
    *,
    session_id: str,
    client_nonce: str,
    server_nonce: str,
    confirm_nonce: str,
    client_public_key: str,
    server_public_key: str,
) -> bool:
    """Constant-time verification of a ``binding_proof``. Never raises."""
    try:
        if not binding_token or not provided_proof:
            return False
        expected = compute_binding_proof(
            binding_token,
            session_id=session_id,
            client_nonce=client_nonce,
            server_nonce=server_nonce,
            confirm_nonce=confirm_nonce,
            client_public_key=client_public_key,
            server_public_key=server_public_key,
        )
        return hmac.compare_digest(
            expected.encode("utf-8"), provided_proof.encode("utf-8")
        )
    except Exception:
        return False


# ---------------------------------------------------------------------------
# Pre-shared-secret token derivation (legacy / out-of-band PSK)
# ---------------------------------------------------------------------------


def derive_binding_token(
    client_nonce: str,
    server_nonce: str,
    session_id: str,
    shared_secret: str,
) -> str:
    """
    Derive a binding token from the handshake nonces and a PRE-SHARED secret.

    Computes ``HMAC-SHA256(shared_secret, client_nonce + "\\x00" + server_nonce + "\\x00" + session_id)``
    and returns the hex digest.

    Only meaningful when ``shared_secret`` was established out-of-band and
    is never transmitted. The handshake's default mechanism is X25519 key
    agreement — see :func:`derive_session_binding_key`.

    Raises:
        ValueError: If shared_secret is empty.
    """
    if not shared_secret:
        raise ValueError("shared_secret must not be empty")
    message = (client_nonce + "\x00" + server_nonce + "\x00" + session_id).encode("utf-8")
    return hmac.new(
        key=shared_secret.encode("utf-8"),
        msg=message,
        digestmod=hashlib.sha256,
    ).hexdigest()


# ---------------------------------------------------------------------------
# Per-message binding
# ---------------------------------------------------------------------------


def canonical_body_digest(body: Any) -> str:
    """SHA-256 (hex) of the canonical JSON form of a message body.

    Canonical JSON: ``json.dumps(body, sort_keys=True, separators=(",", ":"),
    ensure_ascii=False)`` encoded as UTF-8. A ``None`` body hashes as
    ``null``.

    Raises:
        TypeError / ValueError: If *body* is not JSON-serialisable.
    """
    canonical = json.dumps(
        body,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")
    return hashlib.sha256(canonical).hexdigest()


def _message_binding_input(session_id: str, message_id: str, body: Any) -> bytes:
    return (
        session_id + "\x00" + message_id + "\x00" + canonical_body_digest(body)
    ).encode("utf-8")


def create_message_binding(
    session_id: str,
    message_id: str,
    binding_token: str,
    *,
    body: Any,
) -> str:
    """
    Create the per-message HMAC proof for the ``Session-Binding`` header.

    Computes ``HMAC-SHA256(binding_token, session_id + "\\x00" + message_id
    + "\\x00" + hex(SHA-256(canonical_json(body))))`` and returns the hex
    digest. ``body`` is the JSON form of the envelope body as sent on the
    wire.

    Raises:
        ValueError: if ``binding_token`` is empty. An empty token would let
            any sender compute a valid proof — must come from a real handshake.
        TypeError: if ``body`` is not JSON-serialisable.
    """
    if not binding_token:
        raise ValueError("binding_token must not be empty")
    return hmac.new(
        key=binding_token.encode("utf-8"),
        msg=_message_binding_input(session_id, message_id, body),
        digestmod=hashlib.sha256,
    ).hexdigest()


def verify_message_binding(
    session_id: str,
    message_id: str,
    binding_token: str,
    provided_hmac: str,
    *,
    body: Any,
) -> bool:
    """
    Verify a per-message binding proof using constant-time comparison.

    Returns False (never raises) on any input problem so callers can treat
    the result as a simple pass/fail. Specifically:

      * Empty ``binding_token`` → False (a session without a derived token
        cannot have a valid binding proof).
      * Empty or non-ASCII ``provided_hmac`` → False.
      * Non-serialisable ``body`` → False.

    Otherwise recomputes the expected HMAC (which covers the body digest)
    and compares the UTF-8 bytes with ``hmac.compare_digest``.
    """
    try:
        if not binding_token or not provided_hmac:
            return False
        expected = create_message_binding(
            session_id, message_id, binding_token, body=body
        )
        return hmac.compare_digest(
            expected.encode("utf-8"), provided_hmac.encode("utf-8")
        )
    except Exception:
        return False
